Show error message when gcsfuse is not installed

diff --git a/python/pyclash/templates/clash_runner.sh.j2 b/python/pyclash/templates/clash_runner.sh.j2
--- a/python/pyclash/templates/clash_runner.sh.j2
+++ b/python/pyclash/templates/clash_runner.sh.j2
@@ -10,8 +10,12 @@ function __trap_clean_up {
 trap __trap_clean_up EXIT
 
 {% for bucket in gcs_mounts %}
-mkdir -p {{ gcs_mounts[bucket] }}
-gcsfuse --implicit-dirs {{ bucket }} {{ gcs_mounts[bucket] }}
+if ! [ -x "$(command -v gcsfuse)" ]; then
+  echo 'Error: Could not mount bucket. gcsfuse is not installed.' >&2
+else
+  mkdir -p {{ gcs_mounts[bucket] }}
+  gcsfuse --implicit-dirs {{ bucket }} {{ gcs_mounts[bucket] }}
+fi
 {% endfor %}
 
 {% for directory in gcs_target %}
